### Collect logs to {{ logs }}

---
- hosts: nodes

  tasks:
  - name: rm -rf logs
    local_action: file path={{ logs }} state=absent
    run_once: true

  - name: fetch logs to {{ logs }}
    fetch:
      src: "{{ pg_logfile }}"
      dest: "{{ logs }}/{{ inventory_hostname }}.log"
      validate_checksum: no # new logs might constantly arrive
      flat: yes
    tags:
      fetch

  - name: touch logs/united.log
    local_action: copy content="" dest={{ logs }}/united.log
    run_once: true

  - name: unite logs
    local_action: shell cat {{ logs }}/{{ item }}.log >> {{ logs }}/united.log
    with_items: "{{ groups.nodes }}"
    run_once: true

  - name: create symlink to shardlord log
    local_action: file
      src={{ groups['shardlord'][0] }}.log
      dest={{ logs }}/shardlord.log
      force=yes
      state=link
    run_once: true
