### execute psql cmd and print res

---
- hosts: nodes

  environment:
    PATH: "{{ pg_dst }}/bin:{{ ansible_env.HOME }}/root/bin:{{ ansible_env.PATH }}"
    LIBRARY_PATH: "{{ ansible_env.HOME }}/root/lib"
    CPATH: "{{ ansible_env.HOME }}/root/include"
    LD_LIBRARY_PATH: "{{ ansible_env.HOME }}/root/lib"

  tasks:
  - name: psql cmd
    command: psql -p {{ pg_port }} -c {{ cmd }}
    register: out

  - debug: var=out.stdout_lines
