Vagrant.configure("2") do |config|

  config.vm.define "node1" do |node|
    node.vm.box = "ubuntu/xenial64"
    node.vm.network "private_network", ip: "10.42.42.10"
  end

  config.vm.define "node2" do |node|
    node.vm.box = "ubuntu/xenial64"
    node.vm.network "private_network", ip: "10.42.42.20"
  end

  config.vm.define "node3" do |node|
    node.vm.box = "ubuntu/xenial64"
    node.vm.network "private_network", ip: "10.42.42.30"
  end

  # ssh-copy-id
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/ubuntu/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end

end
